kind: Secret
apiVersion: v1
metadata:
  name: credentials
  annotations:
    avp.kubernetes.io/path: "kv/data/credentials"
type: Opaque
stringData:
  password: <password>
  username: <username>
  url: <url>
